---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cqa-ingress
  namespace: shannon
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  tls:
    - hosts:
        - shannon.opendatalab.com
      secretName: shannon-gateway-tls
  rules:
    - host: shannon.opendatalab.com
      http:
        paths:
          - path: /cqa(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cqa-svc
                port:
                  number: 80
